remote_theme: chrisrhymes/bulma-clean-theme
timezone: America/Los_Angeles
permalink: /Sailing/
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num"
footer_menu: footer
hero_image: ../Sailing/assets/images/1986Catalina-min.jpg
hero_darken: true
